#!/usr/bin/env python3
"""Emit tang/src/pk8000/waits_rom.v: the extra clocks the ПК8000's video
controller costs each instruction, as a combinational lookup.

The ПК8000 has no wait-state generator the CPU can see as such; the video
controller holds READY off while it owns the DRAM, and how long that costs
an instruction depends on the opcode, on whether it was fetched from ROM
or RAM, and on whether the display is in the active part of a line in a
40-column mode.  Nobody has the PLM equations; what exists is the table of
MEASURED extra clocks per opcode that Emu80 (Viktor Pykhonin, GPL v3,
src/Pk8000.cpp, class Pk8000CpuWaits) carries, with the tables named
waits12Ram / waits03Ram / waits12Rom / waits03Rom - "12" for modes 1 and 2
or any mode outside the active area, "03" for modes 0 and 3 inside it.
Those numbers are reproduced here as the hardware measurement they are;
the conditional-return and conditional-call rows are overridden in
cpu8080.v by whether the branch was taken, as Emu80 does.

    waits_rom.py > tang/src/pk8000/waits_rom.v

Index: {rom, wide, opcode[7:0]} - rom = fetched from a page that is not
RAM, wide = the 40-column active-area flag.  Output: 5 bits.
"""
import sys

W12RAM = [
    4,6,5,3,3,3,5,4,4,2,5,3,3,3,5,4, 4,6,5,3,3,3,5,4,4,2,5,3,3,3,5,4,
    4,6,16,3,3,3,5,4,4,2,8,3,3,3,5,4, 4,6,11,3,10,10,10,4,4,2,7,3,3,3,5,4,
    3,3,3,3,3,3,5,3,3,3,3,3,3,3,5,3, 3,3,3,3,3,3,5,3,3,3,3,3,3,3,5,3,
    3,3,3,3,3,3,5,3,3,3,3,3,3,3,5,3, 5,5,5,5,5,5,4,5,3,3,3,3,3,3,5,3,
    4,4,4,4,4,4,5,4,4,4,4,4,4,4,5,4, 4,4,4,4,4,4,5,4,4,4,4,4,4,4,5,4,
    4,4,4,4,4,4,5,4,4,4,4,4,4,4,5,4, 4,4,4,4,4,4,5,4,4,4,4,4,4,4,5,4,
    3,6,6,6,5,9,5,9,3,6,6,6,5,15,5,9, 3,6,6,10,5,9,5,9,3,6,6,6,5,15,5,9,
    3,6,6,18,5,9,5,9,3,3,6,4,5,15,5,9, 3,6,6,4,5,9,5,9,3,3,6,4,5,15,5,9]
W03RAM = [
    2,8,5,1,1,1,5,2,2,2,5,1,1,1,5,2, 2,8,5,1,1,1,5,2,2,2,5,1,1,1,5,2,
    2,8,14,1,1,1,5,2,2,2,14,1,1,1,5,2, 2,8,11,1,8,8,8,2,2,2,11,1,1,1,5,2,
    1,1,1,1,1,1,5,1,1,1,1,1,1,1,5,1, 1,1,1,1,1,1,5,1,1,1,1,1,1,1,5,1,
    1,1,1,1,1,1,5,1,1,1,1,1,1,1,5,1, 5,5,5,5,5,5,2,5,1,1,1,1,1,1,5,1,
    2,2,2,2,2,2,5,2,2,2,2,2,2,2,5,2, 2,2,2,2,2,2,5,2,2,2,2,2,2,2,5,2,
    2,2,2,2,2,2,5,2,2,2,2,2,2,2,5,2, 2,2,2,2,2,2,5,2,2,2,2,2,2,2,5,2,
    1,8,8,8,7,10,5,10,1,8,8,8,7,13,5,10, 1,8,8,5,7,10,5,10,1,8,8,5,7,13,5,10,
    1,8,8,12,7,10,5,10,1,1,8,2,7,13,5,10, 1,8,8,2,7,10,5,10,1,1,8,2,7,13,5,10]
W12ROM = [
    1,3,5,1,1,1,2,1,1,1,2,1,1,1,2,1, 1,3,5,1,1,1,2,1,1,1,2,1,1,1,2,1,
    1,3,12,1,1,1,2,1,1,1,5,1,1,1,2,1, 1,3,7,1,6,6,6,1,1,1,4,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 5,5,5,5,5,5,1,5,1,1,1,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,
    1,3,3,3,3,9,2,8,1,3,3,3,3,11,2,8, 1,3,3,4,3,9,2,8,1,3,3,3,3,11,2,8,
    1,3,3,10,3,9,2,8,1,1,3,1,3,11,2,8, 1,3,3,1,3,9,2,8,1,1,3,1,3,11,2,8]
W03ROM = [
    1,3,5,1,1,1,2,1,1,1,2,1,1,1,2,1, 1,3,5,1,1,1,2,1,1,1,2,1,1,1,2,1,
    1,3,8,1,1,1,2,1,1,1,5,1,1,1,2,1, 1,3,5,1,5,5,5,1,1,1,4,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 5,5,5,5,5,5,1,5,1,1,1,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,
    1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1, 1,1,1,1,1,1,2,1,1,1,1,1,1,1,2,1,
    1,3,3,3,3,7,2,6,1,3,3,3,3,9,2,6, 1,3,3,4,3,7,2,6,1,3,3,3,3,9,2,6,
    1,3,3,9,3,7,2,6,1,1,3,1,3,9,2,6, 1,3,3,1,3,7,2,6,1,1,3,1,3,9,2,6]

for t in (W12RAM, W03RAM, W12ROM, W03ROM):
    assert len(t) == 256, len(t)
    assert max(t) < 32

# index bit 9 = rom, bit 8 = wide
tables = {0: W12RAM, 1: W03RAM, 2: W12ROM, 3: W03ROM}

out = []
out.append("`timescale 1ns / 1ps")
out.append("// Generated by tools/waits_rom.py - do not edit, regenerate.")
out.append("// The extra clocks per instruction the video controller costs the CPU,")
out.append("// as measured on the machine and recorded in Emu80's Pk8000CpuWaits")
out.append("// (Viktor Pykhonin).  Index {rom, wide, opcode}; see cpu8080.v.")
out.append("module waits_rom (")
out.append("    input  [9:0] idx,      // {fetched from ROM, 40-col active area, opcode}")
out.append("    output reg [4:0] waits")
out.append(");")
out.append("always @(*) begin")
out.append("    case (idx)")
for hi in range(4):
    t = tables[hi]
    for op in range(256):
        out.append(f"        10'h{hi*256+op:03X}: waits = 5'd{t[op]};")
out.append("        default: waits = 5'd0;")
out.append("    endcase")
out.append("end")
out.append("endmodule")
sys.stdout.write("\n".join(out) + "\n")
