# Generated by tools/gowin_tcl.py - do not edit, regenerate.
# Run from the tang/ directory:  gw_sh build.tcl

set_device -name GW2AR-18C GW2AR-LV18QN88C8/I7

add_file -type verilog "src/top.v"
add_file -type verilog "src/sys_pll.v"
add_file -type verilog "src/i2s_tx.v"
add_file -type verilog "src/pk8000/vm80a.v"
add_file -type verilog "src/pk8000/cpu8080.v"
add_file -type verilog "src/pk8000/waits_rom.v"
add_file -type verilog "src/pk8000/sdram.v"
add_file -type verilog "src/pk8000/pk8000_rom.v"
add_file -type verilog "src/pk8000/ports.v"
add_file -type verilog "src/pk8000/video.v"
add_file -type verilog "src/pk8000/sd_arbiter.v"
add_file -type verilog "src/pk8000/poke.v"
add_file -type verilog "src/pk8000/tape.v"
add_file -type verilog "src/pk8000/fdc.v"
add_file -type verilog "src/pk8000/fdc_rom.v"
add_file -type verilog "src/pk8000/wd1793.sv"
add_file -type verilog "src/pk8000/ide.v"
add_file -type verilog "src/pk8000/hdd_rom.v"
add_file -type verilog "src/pk8000/romdisk.v"
add_file -type verilog "src/pk8000/ay.v"
add_file -type verilog "src/pk8000/ym2149.sv"
add_file -type verilog "src/hdmi/hdmi_packet.v"
add_file -type verilog "src/hdmi/hdmi_serdes.v"
add_file -type verilog "src/hdmi/hdmi_tx.v"
add_file -type verilog "src/hdmi/tmds_channel.v"
add_file -type verilog "src/mister/hid.v"
add_file -type verilog "src/mister/mcu_spi.v"
add_file -type verilog "src/mister/osd_u8g2.v"
add_file -type verilog "src/mister/sd_card.v"
add_file -type verilog "src/mister/sd_rw.v"
add_file -type verilog "src/mister/sdcmd_ctrl.v"
add_file -type verilog "src/mister/sector_dpram.v"
add_file -type verilog "src/mister/sysctrl.v"
add_file -type cst "src/pk8000.cst"
add_file -type sdc "src/pk8000.sdc"

set_option -top_module top
set_option -verilog_std sysv2017
set_option -global_freq 100.000
set_option -rw_check_on_ram 0
set_option -use_sspi_as_gpio 1
set_option -correct_hold_violation 1
set_option -output_base_name pk8000

run all
